module-name: btp-operator
rc-tag: 0.0.201
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/btp-manager:0.0.201
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"

