module-name: btp-operator
rc-tag: 1.1.2
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/btp-manager:1.1.2
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"

