module-name: btp-operator
kind: kyma
rc-tag: 1.2.22
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/btp-manager:1.2.22
mend:
  language: golang-mod
  exclude:
    - "**/*_test.go"
checkmarx-one:
  preset: go-default
  exclude:
    - "**/*_test.go"
