---
# Source: sap-btp-operator/templates/configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sap-btp-operator-config
  namespace: kyma-system
  labels:
    "services.cloud.sap.com/managed-by-sap-btp-operator": "true"
data:
  CLUSTER_ID: b5228518-3786-46f3-a9c1-3a7861a3df8c
  MANAGEMENT_NAMESPACE: kyma-system
  RELEASE_NAMESPACE: kyma-system
  ENABLE_LIMITED_CACHE: "true"
  ALLOW_CLUSTER_ACCESS: "true"
