---
# Source: sap-btp-operator/templates/configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sap-btp-operator-config
  namespace: kyma-system
  labels:
    "services.cloud.sap.com/managed-by-sap-btp-operator": "true"
data:
  CLUSTER_ID: b7223667-7779-40c8-a091-4c9e40aa1c59
  MANAGEMENT_NAMESPACE: kyma-system
  RELEASE_NAMESPACE: kyma-system
  ENABLE_LIMITED_CACHE: "false"
  ALLOW_CLUSTER_ACCESS: "true"
