---
# Source: sap-btp-operator/templates/configmap.yml
apiVersion: v1
data:
  CLUSTER_ID: b1e7472c-3210-4793-a07e-70bfc43f7cfb
  MANAGEMENT_NAMESPACE: kyma-system
  RELEASE_NAMESPACE: kyma-system
  ALLOW_CLUSTER_ACCESS: "true"
kind: ConfigMap
metadata:
  name: sap-btp-operator-config
  namespace: kyma-system
