apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: kyma-priority
  labels: {}
value: 2100000
globalDefault: false
description: "Scheduling priority of the btp-operator module. Must not be blocked by unschedulable user workloads."
