apiVersion: operator.kyma-project.io/v1alpha1
kind: BtpOperator
metadata:
  labels:
    app.kubernetes.io/name: btpoperator
    app.kubernetes.io/instance: btpoperator-sample
    app.kubernetes.io/part-of: btp-manager
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: btp-manager
  name: btpoperator-sample
  finalizers:
    - kubernetes
spec:
  # TODO(user): Add fields here
