name: Label validator
on:
  pull_request_target:
    types: ["opened", "labeled", "unlabeled", "synchronize", "reopened", "ready_for_review", "edited"]
    branches: [ "main" ]

permissions:
  discussions: write
  pull-requests: write
  
jobs:
  validate-labels: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Validate labels
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: scripts/label_validator.sh "PR" ${{ github.event.pull_request.number }} ${{ github.event.action }}
